// Generated by CoffeeScript 1.4.0
(function() {
  var BinaryTree, BinaryTreeUtility;

  BinaryTree = window.TreeStructure.Binary;

  BinaryTreeUtility = window.TreeStructure.BinaryUtility;

  describe("BinaryTreeUtility", function() {
    var testTree, utility;
    testTree = void 0;
    utility = void 0;
    beforeEach(function() {
      testTree = new BinaryTree();
      return utility = new BinaryTreeUtility();
    });
    describe("When Tree Is Empty", function() {
      return it("it should have a height of 0", function() {
        return expect(utility.treeHeight(testTree)).toBe(0);
      });
    });
    describe("When Tree Has One Child", function() {
      beforeEach(function() {
        return testTree.addChild(new BinaryTree());
      });
      return it("it should have a height of 1", function() {
        return expect(utility.treeHeight(testTree)).toBe(1);
      });
    });
    return describe("When Tree Has Four Levels", function() {
      var testTree2, testTree3;
      testTree2 = void 0;
      testTree3 = void 0;
      beforeEach(function() {
        testTree2 = new BinaryTree();
        testTree2.addChild(new BinaryTree());
        testTree3 = new BinaryTree();
        testTree3.addChild(testTree2);
        return testTree.addChild(testTree3);
      });
      return it("it should have a height of 3", function() {
        return expect(utility.treeHeight(testTree)).toBe(3);
      });
    });
  });

}).call(this);
